test_sshd.test: fixup to distcheck failure
Fixes:
```
ERROR: test_sshd.test - missing test plan
ERROR: test_sshd.test - exited with status 1
```
Ref: https://github.com/libssh2/libssh2/actions/runs/5322354271/jobs/9638694218#step:10:532

Caused by trying to create the log file in a read-only directory.

Follow-up to 299c2040625830d06ad757d687807a166b57d6de
Closes #1099